apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-api-deployment
  labels:
    app: diabetes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diabetes-api
  template:
    metadata:
      labels:
        app: diabetes-api
    spec:
      containers:
        - name: diabetes-api
          image: diabetes-api:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
